travis:
  secure:
    BINSTAR_TOKEN: BVvVmawlNggJKry4gASrAhzTcQcRJvdLHcegIi8IJglq1555ggycUN2KJL2q/qAVqLCNuOmbg+qTcsRbtRT/7KeFgIdpCQiKFrK1TnT+E4CPorFA08YZRpoai+gxHP71Vd5PMNuk5pG6JVnxxXBOu6x8ittibrt9YIkp1Oi89g4pwcVV7CeChreWLasCZHlQDnsgptY7ZonKVaTwvOx5QJOtsQg83SaHhJcj9X9vC29MdIVxwkxIwVeGCJ0KT+nFnldpVt7wv16KLTQ+P9RC76xg6bVf/s3xKoJ+DDy/c7NUAIs8/4wTPEFPltgrB0fAABnU2E6QrwmSwRUC8ZwROs2SPwQn08RH77JEhGCcG+ewgWosWDg3Pyfnf2j4jT6TPj8VaS3rG3l1qGGoGx5GZML5hd7WF2NNo/yjhlR9p0vH4B3o/IEUW9AHiRlnyi7KScjb/MvrBZsNw66eg5G9Z4gPLrcfZ3WWVl+6Rms79VC3dp33bMeR38YhxGJnD+dF05w7h9XdyluM6kVw+TnPI6ESJ68bLx5R+WYGla6160ZXdqpql+pZWALRiDXW1Mt2RAaVXIjDcu13kbXmuwtdFG43h4gz2LJccrrR15ZJm5t9soabHlQRjR+SwH0TNodCI8W5mPOAqrNF4L7lSyh8MZtgjEArq0YnN5fEGAPDhns=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
