travis:
  secure:
    BINSTAR_TOKEN: lVsf7RsioHbscMeJbb9qpeMgG4BpXDXs2o/AqhS1eZwnGCG0TsyY6Bm535pz2VT8ExXV8jt8RdplfDewLz0WhuaUpkP2A17FY49X3wc5SkhB//5M2CmsM5eEA99NENNeSdZnB+YCxjWra+ZlNB/LwlNdswjUGayiArX/NIEJoj077nnw/wiPWQtNgA4i0D0pKr9zx2YAFaCU7BH4kJMxJ3TFuloB3BaLMhVKBsLJhXXbVKkeM3DUKkH2vSUn51PlB8QkOSvUqV7kLr41IJL/xs9lrdYleWQ8kEK46Z2KF7hZ+oRppO9QNpEG8gunpoqwis4ARTwF6q4cb2cVMMaJ3H+QY7Me1/I+fuQYCr7fbslCpgBB4hahpTJR6BQ8T1t1mRZmWmDkB6fNCid0OpBs9i/3K5/Y/enIf4U+glsR6z41kcty280Mokntmi+uVx3z2itKYg8xVFhCfnjzfXneCDAmtj8xshO3LE214Uboiv0U/W7EpnxDVH+DzHGHqvhZMgczGmrvG2juSJdEtQb7jdkIIYnOfAl4vzKFmRcanrtA9gafHYGpHDKI6Cyid2QH+eQQLkNj+zns3/gA5N16A3KSzo9HQfUFzErRlVaEMdIkCeELSVrbBAMRz7YYGLWRSTOuFFCJgSNvzkdNbyGgWf3BOJgeUfXdxxMt51wRjYo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
