travis:
  secure:
    BINSTAR_TOKEN: JrkEBkIpj93a/um3i2dlexHluhoEwsCzK0dgiXLDnoyuVzqYdvsL5CKlnBX9ekPN3I1x3WXYFkxafxNsSBCjzsTseZVDDwQ631jXDP0TVcPABT9IJtbpn7WNxZQrkikaPlTscvj5nCqwwEwB6R0+BQX0ON1Adcqc+SmH7BJzunOlZL8KAw1O35MnNGBm53W4H72VeVVywd2xkq08WlEagSROYJBzuIyu8+F15q2D5v1wSbD4BwHt8T727nHgJTQW/oQ8x+D8RfrBgrnKBEgS5ys4RmbgZguMiVvWp7fZ7aK4x9y0thUfPgjnbGp07ChnSeGgODWOct8Cg9eE6pDblZK87fh4u4kXT9Alky6jzD86dX4N4DN5W+VBzCD/E2XMaCHZCXM3nZ7paeCNaasUAFOJpnn1QtKQNdjADt4y/A192mN/wNyVjeWIXS2O/36BkbxDHftchmQQHDk6xjzqrxXzOSnyyva5S/Ln7oCvMAPbX1GKCQ/NBeUjm3TRVfP1ZkmzfKgE0287+5x9GqsG4s2CqozKeKM4tEGE8h/AuZHDdBqoi9l3TKTiFsNfgBTA5H2L1lRVPQgIhRappyCq1zQmoaxxN0snpb9omJd2IVjhEUcsT6G5+QjyuJ5ch8HHav6hPREcx525HqE5bKjXht+vqumEVDsv+Eo+Lqp7k+E=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
