travis:
  secure:
    BINSTAR_TOKEN: SVbnL4A5LEQbNJAnCOpHzwEqwHQFHoJNW0zZUfyPMFe0PqguDDktX2vCDZRIto5nXerDAW/sk9uTaAHWPGSVmquL38m72gwniAYNsmWYbMrBusno7HM8Kphtr94k/gD7epUa6ufXIBublEzgp/LeZX65gbvzkzOp2H7lwr4hY1rz4RfOirPCe+M3/cylDhdEMXHxNngm7Cb6l5rhRF2FYDOy0X5HPJ7l5RsHXmvalm1AwT0thnrBdDPchbU7b4iiJvltXrol3dl1pMewh3JgmpZkb8lxFDzTHUDFY/UOyxBPQYg8fhkKneyUaW0Cw6BPnvNP3kW2+KbXVw4HpAo9IK+e0Rcbu1g4HG/G9Z+EBoyxdveYn9l76Ul6e8Kq2jVkibWRTKA2z0z8RY2o3BcjTHRIu/IGaVJedyy5+vK7zcwPV8n+RESWXv6sEhsghN8dEFNrYkk4rOqVJfGHLNi7Piqes+s0saFR8cbzLcZ58JXrY4GXcgGophhfs5g3AYLdxYMIOs3qdfBKbLqlJj7KejG057rUzJghGyMFVM9Z4BWrsJoyIe0a2raFLreAmPcVvmDPO6sFkhs15PivzBSTv72dyHg6yMC6fn2uocZc4/ZENwdEaOP0bJbttyqGWhQoJF42GwEiU8JPavfXO7QuqSvGlqQN+jJ5APbFEdSmSJ4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
