travis:
  secure:
    BINSTAR_TOKEN: eZz7ddvTEyIPbGoH9UH4UjI1a1bTiDXLqGmjPotYdnm1qvoGET0WpFJIVbqyy+8z8CKyhEh/xDzxO52a9FKKMiooBZh6AljdmMuU1uO2grcJgJkL6YAuaVisSsMMqfnQnL2IH83nY8Z5BVcawsnKLsibD536W4mMThJyfa77eMTbOojyENixpL9IpbYGPcJYHgTkMP+3abbDDifC+Qu5uMgSUb9fGp+uqzz2GsmWuAPbnnrCA0bR7ENM96BjlgwufyyCA2weCocDWdB9CWdwxxrNnMamfHbe9B9nJkW6VNtcmMU2VmnYi0b3sYPyxew8ju3C2KJ1Voku3PiNB9yQhP7iBcIB4xbbEf0GdZhd+1L5xsgb0nnm/7Exm/Slkj68nclzRRowEk1qnvRTCoQ9qEvj65B9kdy4rxyMeZ6StSV82bst1cxUpMOsHcej/+W82MpTKPwjjU3HXP7PuwCj5pbyOsZ+8s8ps5hc7xqodNYeKQHTPhRDUEA+gt9N8ri6NojFY7gdrpcV5dYPoEEtPxWeMBK2hyW59NV6Tf++Z0Owc6GBMY+sNX+51Jrb5gDiXFd4Ab1G7iZf5J5KaBKC6Q0WdScdAmCbR9FWmrB5o66Wti6bGYGB8jnNv+jHL/oMqNaAUL/AM9Q0oVCwoC+1GX5J0qMEzS9Xb+usAdmZIvQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
