travis:
  secure:
    BINSTAR_TOKEN: aUBjAC+deHFeJrtPLHtVrsIeE6Lk1hjAY6Kv3YgLY/t4nQNS6ucajkqJn8vDc8mRMBxgWJDQtAtj1cs1+EnbmVJynBQMT332SFTYfHWSUYqgzh+IboDAiQwpTUOMaM0c5vXENdwJBXci3eKJiuWBKKWht0zmwYXNYhymy7j4b3ssgiPc5P/j0RejHfQhPUf0vDjAGpFO18imcxQs4/UYs87pycagVREns5ZwuoV9p6BInK1dPh7/rl3AIy8hjZCfqeI0X8pizT8IzJXCUnAosZB//k6taR5XXCwwvWUte4R8vhDB5OXC3dUu9CMfcFF2Ny2Kf/PCkgav4uEbDL18JGHvgaFYMKKSg1Ks5GWVhp6x/fINygkBCINuGBR1SH2x9BBib21bvNJUE89mcApdhoqO8SRta8AJ7m8paEew+0MfF9US4O/7O3F1Gyp7hJU9F7yQo048FhdB7PyJKK1+g90MLPH7iwQSAbN1r2EpGSbS1XfYpOL8yLZekT3xubRBP5y10TJkpyA4C+0w8smgnO4nL5OYjY7HxxbP1f4B0K0D9aS9TePO7Kcg1KgSNFYc3EP9dgQ4xWmb1iehCDFxM/Vp/O+3VUjD0YufIpUsOxNk0Zum6ewGqD1cegM/M9DM6VEGsmD1fjdB94ZZC8Hm1f5JY9L6ppmhy/YloSVt8rI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
